const KRISPY_KREME_CATEGORIES = [
  "KREME DEALS",
  "FATHER'S DAY DOUGHNUT",
  "MINIONS & MONSTERS DOUGHNUTS",
  "SINGLE DOUGHNUTS",
  "DOUGHNUT BOXES",
  "HOT COFFEE",
  "COLD COFFEE",
  "BAKED CREATIONS",
  "CHILLERS",
  "FROZZE SHAKE",
  "ICE KREME",
  "KREME SHAKE",
  "COFFEE BAG",
  "SOFT DRINKS",
  "COMPLIMENTARY",
  "PRE-ORDER",
];

const BN_CATEGORIES = [
  "BN DRINKS",
  "BN BURGERS",
  "BN APPETIZERS",
  "BN ADD-ONS",
  "BN DEALS",
  "BN COMBO",
];

const SCOOPD_CATEGORIES = [
  "SODA",
  "CHICK N CONE",
  "SCOOP'D DEALS",
  "ICE CREAM",
  "PASTRIES",
  "SCOOPD SHAKES",
  "WAFFLES",
  "TOPPINGS",
  "SAVOURY",
  "DESSERTS",
  "SUNDAE",
  "SCOOPD EXTRAS",
  "EXTRAS",
  "SNACKS",
  "COFFEE DRINKS",
];

export { BN_CATEGORIES, KRISPY_KREME_CATEGORIES, SCOOPD_CATEGORIES };
